appointments: https://stable.s3.ap-south-1.amazonaws.com/msf-release-2.6.2/appointments-1.3.0-SNAPSHOT-2.1.0.omod
bahmni_core: https://stable.s3.ap-south-1.amazonaws.com/msf-release-2.6.2/bahmnicore-0.93-SNAPSHOT-2.6.0.omod
bahmni_ie_apps: https://stable.s3.ap-south-1.amazonaws.com/msf-release-2.6.2/bahmni.ie.apps-1.1.0-SNAPSHOT-2.5.0.omod
bahmniapps: https://stable.s3.ap-south-1.amazonaws.com/msf-release-2.6.2/bahmniapps-2.6.2.zip
implementer_interface: https://stable.s3.ap-south-1.amazonaws.com/msf-release-2.6.2/bahmni-implementer-interface-91-2.6.1.noarch.rpm
appointment_frontend: https://stable.s3.ap-south-1.amazonaws.com/msf-release-2.6.2/appointment-frontend-2.6.2.zip
emr_api_omod: https://stable.s3.ap-south-1.amazonaws.com/msf-release-2.6.2/emrapi-omod-1.24.7-2.1.0-SNAPSHOT.omod
event_omod: https://stable.s3.ap-south-1.amazonaws.com/msf-release-2.6.2/event-2.8.0-2.1.0.omod
uiframework: https://stable.s3.ap-south-1.amazonaws.com/msf-release-2.6.2/uiframework-3.19-2.1.0.omod
patient_identifier_generator: https://stable.s3.ap-south-1.amazonaws.com/msf-release-2.6.2/patientidentifiergenerator-0.1.0-2.0.0.omod